### PR TITLE
Update to spdlog 1.9.1

### PR DESCRIPTION
**Pull request by clalancette**
This way we match what is in Ubuntu 22.04

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16702/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11282/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17097/)
* Windows Debug [Build Status](http://ci.ros2.org/job/ci_windows/17098/)

**Comment by quarkytale** [comment]
Retriggered Windows CI [Build Status](https://ci.ros2.org/job/ci_windows/17389/)

**Review by quarkytale — APPROVED** [review]
Sorry this got backtracked. Works for me!

**Comment by clalancette** [comment]
Here's a new CI for this since it has been a while:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17088/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11639/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17507/)

**Comment by quarkytale** [comment]
There seems to be a persistent syntax error at `C:\ci\ws\install\include\spdlog\fmt\bundled\core.h:536`. I'll check on my system again.

**Comment by clalancette** [comment]
> There seems to be a persistent syntax error at `C:\ci\ws\install\include\spdlog\fmt\bundled\core.h:536`. I'll check on my system again.

Good point.  I'll see what I can find out about it.

**Comment by clalancette** [comment]
I put a fix in to ignore cppcheck warnings on the bundled library.  Here's another CI to check:


* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17123/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11670/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17539/)

**Comment by quarkytale** [comment]
Retriggered windows CI [Build Status](https://ci.ros2.org/job/ci_windows/17555/)

**Comment by clalancette** [comment]
> Retriggered windows CI [Build Status](https://ci.ros2.org/job/ci_windows/17555/)

Sigh, there is something else I need to fix, down in the `rcl_logging` layer.  It won't work until then.

**Comment by clalancette** [comment]
All right, I've done the necessary updates to `rcl_logging`, which will have to be merged before this PR.  Here's new CI for the both of them:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17330/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11867/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17838/)

**Comment by clalancette** [comment]
@quarkytale I finally had time to come back to this, and I finally got this to go green on Windows.  We'll need the change in ros2/rcl_logging#93 as well, so I'd appreciate if you could review them both.

**Review by quarkytale — APPROVED** [review]

**Comment by clalancette** [comment]
CI is finally happy with the changes from ros2/rcl_logging#93 .  Going ahead and merging.  Thanks for the review!

**Comment by clalancette** [comment]
I just realized I should have run Windows Debug CI.  Here it is:

* Windows Debug [Build Status](http://ci.ros2.org/job/ci_windows/17885/)

**Pull request merged**
