### PR TITLE
Silence warning from GNUInstallDirs on Windows.

### LINKED ISSUE #9: CMake warning on Windows
First appearance in this packaging job https://ci.ros2.org/view/packaging/job/packaging_windows/1700/

```
  Performing configure step for 'spdlog-1.5.0'

  CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/GNUInstallDirs.cmake:225 (message):

    Unable to determine default CMAKE_INSTALL_LIBDIR directory because no

    target architecture is known.  Please enable at least one language before

    including GNUInstallDirs.

  Call Stack (most recent call first):

    CMakeLists.txt:9 (include)
```

### PR DESCRIPTION
**Pull request by clalancette**
By importing https://github.com/gabime/spdlog/commit/1b4621962fd6787b0006ca641944aa5e60b570e5

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

This should fix #9 , and make CI a little bit happier on Windows.

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10193/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5746/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8286/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10078/)

**Comment by clalancette** [comment]
All right, I finally figured out how to make Windows happy.  Ready for a review.

**Review by hidmic — APPROVED** [review]
LGTM

**Comment by clalancette** [comment]
Thanks for the review, merging.

**Pull request merged**
