### PR TITLE
build shared lib only if BUILD_SHARED_LIBS is set

### PR DESCRIPTION
**Pull request by hannes09**
with this change spdlog_vendor also build as a static lib if BUILD_SHARED_LIBS=OFF

### CODE REVIEW

**Comment by methylDragon** [comment]
Hi there! With the merge of https://github.com/ament/ament_cmake/pull/390 , we can now merge this, with one change.
Could you help to add this line here, please? Once you do I'll launch CI and work towards getting this merged!

```
find_package(ament_cmake REQUIRED)
ament_add_default_options() <<<--- THIS ONE! ⭐
```

**Review by methylDragon — CHANGES_REQUESTED** [review]
See above post

**Comment by methylDragon** [comment]
Bumping @hannes09

**Comment by hannes09** [comment]
I have added `ament_add_default_options`, but now the build fails.

**Comment by methylDragon** [comment]
@ros-pull-request-builder retest this please

**Review by methylDragon — APPROVED** [review]

**Comment by clalancette** [comment]
Was there a CI job run on this one (and the others)?

**Comment by methylDragon** [comment]
> Was there a CI job run on this one (and the others)?

My bad.. I got confused with the Rpr job

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16959/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11523/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17357/)

**Pull request merged**
